// flow-typed signature: be563e131b23f34ae3735b0f91696ecf
// flow-typed version: <<STUB>>/@types/node_v^12.20.43/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
