// flow-typed signature: 9ad42c081c9d9115e9d55f812bc34352
// flow-typed version: <<STUB>>/@types/react_v^17.0.39/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
