// flow-typed signature: 83a1fdf64182b4ad04fbf8d963536202
// flow-typed version: <<STUB>>/@types/redux-mock-store_v^1.0.3/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-mock-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-mock-store' {
  declare module.exports: any;
}
