// flow-typed signature: 96583fe6c1d99b368e8a89f72b53b5b9
// flow-typed version: <<STUB>>/@types/shallowequal_v^1.1.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/shallowequal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/shallowequal' {
  declare module.exports: any;
}
