// flow-typed signature: f0e04ad6bb8339502cb8551a8187626c
// flow-typed version: <<STUB>>/oberon-prettier-config_v^1.0.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oberon-prettier-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oberon-prettier-config' {
  declare module.exports: any;
}
