// flow-typed signature: 87bc5483e9ed3c453ab3af104a23e2bc
// flow-typed version: <<STUB>>/orval_v^6.6.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'orval'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'orval' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'orval/dist/bin/orval' {
  declare module.exports: any;
}

declare module 'orval/dist/chunk-AGCNR7JW' {
  declare module.exports: any;
}

declare module 'orval/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'orval/dist/bin/orval.js' {
  declare module.exports: $Exports<'orval/dist/bin/orval'>;
}
declare module 'orval/dist/chunk-AGCNR7JW.js' {
  declare module.exports: $Exports<'orval/dist/chunk-AGCNR7JW'>;
}
declare module 'orval/dist/index' {
  declare module.exports: $Exports<'orval/dist'>;
}
declare module 'orval/dist/index.js' {
  declare module.exports: $Exports<'orval/dist'>;
}
