// flow-typed signature: 35abe0c5ee7a8c161e84150151583777
// flow-typed version: <<STUB>>/ts-jest_v^27.1.3/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ts-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ts-jest/cli' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/config/init' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/config/migrate' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/help' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/helpers/presets' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/compiler/compiler-utils' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/compiler' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/compiler/ts-compiler' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/compiler/ts-jest-compiler' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/config/config-set' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/config' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/config/paths-to-module-name-mapper' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/constants' {
  declare module.exports: any;
}

declare module 'ts-jest/dist' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/presets/create-jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/raw-compiler-options' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/transformers/hoist-jest' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/transformers/path-mapping' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/ts-jest-transformer' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/types' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/backports' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/get-package-version' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/importer' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/json' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/jsonable-value' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/logger' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/memoize' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/messages' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/normalize-slashes' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/sha1' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/testing' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/ts-error' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils/version-checkers' {
  declare module.exports: any;
}

declare module 'ts-jest/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/preprocessor' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/default-esm/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/default/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/presets' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/js-with-babel-esm/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/js-with-babel/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/js-with-ts-esm/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/js-with-ts/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ts-jest/cli.js' {
  declare module.exports: $Exports<'ts-jest/cli'>;
}
declare module 'ts-jest/dist/cli/config/init.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/config/init'>;
}
declare module 'ts-jest/dist/cli/config/migrate.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/config/migrate'>;
}
declare module 'ts-jest/dist/cli/help.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/help'>;
}
declare module 'ts-jest/dist/cli/helpers/presets.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/helpers/presets'>;
}
declare module 'ts-jest/dist/cli/index' {
  declare module.exports: $Exports<'ts-jest/dist/cli'>;
}
declare module 'ts-jest/dist/cli/index.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli'>;
}
declare module 'ts-jest/dist/compiler/compiler-utils.js' {
  declare module.exports: $Exports<'ts-jest/dist/compiler/compiler-utils'>;
}
declare module 'ts-jest/dist/compiler/index' {
  declare module.exports: $Exports<'ts-jest/dist/compiler'>;
}
declare module 'ts-jest/dist/compiler/index.js' {
  declare module.exports: $Exports<'ts-jest/dist/compiler'>;
}
declare module 'ts-jest/dist/compiler/ts-compiler.js' {
  declare module.exports: $Exports<'ts-jest/dist/compiler/ts-compiler'>;
}
declare module 'ts-jest/dist/compiler/ts-jest-compiler.js' {
  declare module.exports: $Exports<'ts-jest/dist/compiler/ts-jest-compiler'>;
}
declare module 'ts-jest/dist/config/config-set.js' {
  declare module.exports: $Exports<'ts-jest/dist/config/config-set'>;
}
declare module 'ts-jest/dist/config/index' {
  declare module.exports: $Exports<'ts-jest/dist/config'>;
}
declare module 'ts-jest/dist/config/index.js' {
  declare module.exports: $Exports<'ts-jest/dist/config'>;
}
declare module 'ts-jest/dist/config/paths-to-module-name-mapper.js' {
  declare module.exports: $Exports<'ts-jest/dist/config/paths-to-module-name-mapper'>;
}
declare module 'ts-jest/dist/constants.js' {
  declare module.exports: $Exports<'ts-jest/dist/constants'>;
}
declare module 'ts-jest/dist/index' {
  declare module.exports: $Exports<'ts-jest/dist'>;
}
declare module 'ts-jest/dist/index.js' {
  declare module.exports: $Exports<'ts-jest/dist'>;
}
declare module 'ts-jest/dist/presets/create-jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/dist/presets/create-jest-preset'>;
}
declare module 'ts-jest/dist/raw-compiler-options.js' {
  declare module.exports: $Exports<'ts-jest/dist/raw-compiler-options'>;
}
declare module 'ts-jest/dist/transformers/hoist-jest.js' {
  declare module.exports: $Exports<'ts-jest/dist/transformers/hoist-jest'>;
}
declare module 'ts-jest/dist/transformers/path-mapping.js' {
  declare module.exports: $Exports<'ts-jest/dist/transformers/path-mapping'>;
}
declare module 'ts-jest/dist/ts-jest-transformer.js' {
  declare module.exports: $Exports<'ts-jest/dist/ts-jest-transformer'>;
}
declare module 'ts-jest/dist/types.js' {
  declare module.exports: $Exports<'ts-jest/dist/types'>;
}
declare module 'ts-jest/dist/utils/backports.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/backports'>;
}
declare module 'ts-jest/dist/utils/get-package-version.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/get-package-version'>;
}
declare module 'ts-jest/dist/utils/importer.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/importer'>;
}
declare module 'ts-jest/dist/utils/index' {
  declare module.exports: $Exports<'ts-jest/dist/utils'>;
}
declare module 'ts-jest/dist/utils/index.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils'>;
}
declare module 'ts-jest/dist/utils/json.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/json'>;
}
declare module 'ts-jest/dist/utils/jsonable-value.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/jsonable-value'>;
}
declare module 'ts-jest/dist/utils/logger.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/logger'>;
}
declare module 'ts-jest/dist/utils/memoize.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/memoize'>;
}
declare module 'ts-jest/dist/utils/messages.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/messages'>;
}
declare module 'ts-jest/dist/utils/normalize-slashes.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/normalize-slashes'>;
}
declare module 'ts-jest/dist/utils/sha1.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/sha1'>;
}
declare module 'ts-jest/dist/utils/testing.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/testing'>;
}
declare module 'ts-jest/dist/utils/ts-error.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/ts-error'>;
}
declare module 'ts-jest/dist/utils/version-checkers.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils/version-checkers'>;
}
declare module 'ts-jest/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/jest-preset'>;
}
declare module 'ts-jest/preprocessor.js' {
  declare module.exports: $Exports<'ts-jest/preprocessor'>;
}
declare module 'ts-jest/presets/default-esm/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/default-esm/jest-preset'>;
}
declare module 'ts-jest/presets/default/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/default/jest-preset'>;
}
declare module 'ts-jest/presets/index' {
  declare module.exports: $Exports<'ts-jest/presets'>;
}
declare module 'ts-jest/presets/index.js' {
  declare module.exports: $Exports<'ts-jest/presets'>;
}
declare module 'ts-jest/presets/js-with-babel-esm/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/js-with-babel-esm/jest-preset'>;
}
declare module 'ts-jest/presets/js-with-babel/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/js-with-babel/jest-preset'>;
}
declare module 'ts-jest/presets/js-with-ts-esm/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/js-with-ts-esm/jest-preset'>;
}
declare module 'ts-jest/presets/js-with-ts/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/js-with-ts/jest-preset'>;
}
declare module 'ts-jest/utils/index' {
  declare module.exports: $Exports<'ts-jest/utils'>;
}
declare module 'ts-jest/utils/index.js' {
  declare module.exports: $Exports<'ts-jest/utils'>;
}
