// flow-typed signature: 068cb80e86986ad9c0117f6069cf36b9
// flow-typed version: <<STUB>>/tslint-config-oberon_v^1.0.4/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslint-config-oberon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslint-config-oberon' {
  declare module.exports: any;
}
